const { withMainApplication } = require('@expo/config-plugins');

// Real-device crash report: "Exception in HostFunction:
// PreviewView.previewOutput: Cannot cast dynamic to a jsi::Value type.
// Please use the 'useRawPropsJsiValue' feature flag..." as soon as the
// biometric palm step's <Camera outputs={[photoOutput]}> rendered.
// react-native-vision-camera's Nitro-Modules-based PreviewView needs
// props delivered as jsi::Value, but this React Native feature flag
// defaults to false (folly::dynamic representation instead) -- see
// react-native/.../internal/featureflags/ReactNativeFeatureFlagsDefaults.kt.
//
// Two earlier attempts at this fix both made things WORSE before landing
// here:
//   1. ReactNativeFeatureFlags.override(...) before loadReactNative() ->
//      startup crash, "SoLoader.init() not yet called" (overriding a
//      flag touches JNI-backed code that needs SoLoader already
//      initialized, which normally only happens inside loadReactNative).
//   2. Calling override() again after loadReactNative() -> startup
//      crash, "Feature flags cannot be overridden more than once"
//      (loadReactNative() already calls DefaultNewArchitectureEntryPoint
//      .load(), which does its own override() for ReleaseLevel.STABLE;
//      the API only allows exactly one override() call per process).
//
// The actual fix: let loadReactNative()'s own override happen
// unmodified, then layer ours on top via dangerouslyForceOverride --
// the API's sanctioned mechanism for exactly this. Our provider extends
// ReactNativeNewArchitectureFeatureFlagsDefaults(true) (the documented
// extension point for "internal apps migrating to the new architecture"),
// replicating what ReactNativeFeatureFlagsOverrides_RNOSS_Stable_Android
// sets (that class itself isn't `open`, so can't be subclassed
// directly) plus our one addition.
//
// android/ is regenerated by `expo prebuild`, so the fix lives here (a
// config plugin), not as a hand-edit of the generated MainApplication.kt,
// or the next clean prebuild would silently drop it and reintroduce the
// crash.
function withRawPropsJsiValueFix(config) {
  return withMainApplication(config, (config) => {
    const isKotlin = config.modResults.language === 'kt';
    if (!isKotlin) {
      throw new Error('withRawPropsJsiValueFix expects a Kotlin MainApplication (got ' + config.modResults.language + ')');
    }

    let contents = config.modResults.contents;

    if (!contents.includes('AppFeatureFlags')) {
      contents = contents.replace(
        'import com.facebook.react.defaults.DefaultReactNativeHost',
        'import com.facebook.react.defaults.DefaultReactNativeHost\n' +
          'import com.facebook.react.internal.featureflags.ReactNativeFeatureFlags\n' +
          'import com.facebook.react.internal.featureflags.ReactNativeNewArchitectureFeatureFlagsDefaults'
      );

      contents = contents.replace(
        'class MainApplication : Application(), ReactApplication {',
        'private class AppFeatureFlags : ReactNativeNewArchitectureFeatureFlagsDefaults(true) {\n' +
          '  override fun useShadowNodeStateOnClone(): Boolean = true\n' +
          '  override fun useRawPropsJsiValue(): Boolean = true\n' +
          '}\n\n' +
          'class MainApplication : Application(), ReactApplication {'
      );

      contents = contents.replace(
        'loadReactNative(this)\n',
        'loadReactNative(this)\n' +
          '    ReactNativeFeatureFlags.dangerouslyForceOverride(AppFeatureFlags())\n'
      );
    }

    config.modResults.contents = contents;
    return config;
  });
}

module.exports = withRawPropsJsiValueFix;
