const { withMainApplication } = require('@expo/config-plugins');

// Real-device crash report: "Exception in HostFunction:
// PreviewView.previewOutput: Cannot cast dynamic to a jsi::Value type.
// Please use the 'useRawPropsJsiValue' feature flag..." as soon as the
// biometric palm step's <Camera outputs={[photoOutput]}> rendered.
// react-native-vision-camera's Nitro-Modules-based PreviewView needs
// props delivered as jsi::Value, but this React Native feature flag
// defaults to false (folly::dynamic representation instead) -- see
// react-native/.../internal/featureflags/ReactNativeFeatureFlagsDefaults.kt.
//
// First attempt at this fix (override() alone, before loadReactNative())
// caused a WORSE regression: a startup crash --
// "ExceptionInInitializerError ... SoLoader.init() not yet called" at
// ReactNativeFeatureFlagsCxxInterop.<clinit>, because reading/overriding
// a flag touches JNI-backed native code that needs SoLoader initialized
// first. SoLoader.init() is safe to call again later (idempotent), so
// calling it here first doesn't conflict with loadReactNative()'s own
// init.
//
// android/ is regenerated by `expo prebuild`, so the fix lives here (a
// config plugin), not as a hand-edit of the generated MainApplication.kt,
// or the next clean prebuild would silently drop it and reintroduce the
// crash.
function withRawPropsJsiValueFix(config) {
  return withMainApplication(config, (config) => {
    const isKotlin = config.modResults.language === 'kt';
    if (!isKotlin) {
      throw new Error('withRawPropsJsiValueFix expects a Kotlin MainApplication (got ' + config.modResults.language + ')');
    }

    let contents = config.modResults.contents;

    if (!contents.includes('ReactNativeFeatureFlags.override')) {
      contents = contents.replace(
        'import com.facebook.react.defaults.DefaultReactNativeHost',
        'import com.facebook.react.defaults.DefaultReactNativeHost\n' +
          'import com.facebook.react.internal.featureflags.ReactNativeFeatureFlags\n' +
          'import com.facebook.react.internal.featureflags.ReactNativeFeatureFlagsDefaults\n' +
          'import com.facebook.react.soloader.OpenSourceMergedSoMapping\n' +
          'import com.facebook.soloader.SoLoader'
      );

      contents = contents.replace(
        'override fun onCreate() {\n    super.onCreate()\n',
        'override fun onCreate() {\n    super.onCreate()\n' +
          '    SoLoader.init(this, OpenSourceMergedSoMapping)\n' +
          '    ReactNativeFeatureFlags.override(object : ReactNativeFeatureFlagsDefaults() {\n' +
          '      override fun useRawPropsJsiValue(): Boolean = true\n' +
          '    })\n'
      );
    }

    config.modResults.contents = contents;
    return config;
  });
}

module.exports = withRawPropsJsiValueFix;
